/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedIdRouteImport } from './routes/feed/$id'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedIdRoute = FeedIdRouteImport.update({
  id: '/feed/$id',
  path: '/feed/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/feed/$id': typeof FeedIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/feed/$id': typeof FeedIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/feed/$id': typeof FeedIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/inngest' | '/api/notifications' | '/feed/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/inngest' | '/api/notifications' | '/feed/$id'
  id: '__root__' | '/' | '/api/inngest' | '/api/notifications' | '/feed/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiInngestRoute: typeof ApiInngestRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  FeedIdRoute: typeof FeedIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$id': {
      id: '/feed/$id'
      path: '/feed/$id'
      fullPath: '/feed/$id'
      preLoaderRoute: typeof FeedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiInngestRoute: ApiInngestRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  FeedIdRoute: FeedIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
