/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedSlugRouteImport } from './routes/feed/$slug'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as FeedSlugIndexRouteImport } from './routes/feed/$slug.index'
import { Route as FeedSlugArticleSlugRouteImport } from './routes/feed/$slug.$articleSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedSlugRoute = FeedSlugRouteImport.update({
  id: '/feed/$slug',
  path: '/feed/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedSlugIndexRoute = FeedSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FeedSlugRoute,
} as any)
const FeedSlugArticleSlugRoute = FeedSlugArticleSlugRouteImport.update({
  id: '/$articleSlug',
  path: '/$articleSlug',
  getParentRoute: () => FeedSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/feed/$slug': typeof FeedSlugRouteWithChildren
  '/feed/$slug/$articleSlug': typeof FeedSlugArticleSlugRoute
  '/feed/$slug/': typeof FeedSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/feed/$slug/$articleSlug': typeof FeedSlugArticleSlugRoute
  '/feed/$slug': typeof FeedSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/feed/$slug': typeof FeedSlugRouteWithChildren
  '/feed/$slug/$articleSlug': typeof FeedSlugArticleSlugRoute
  '/feed/$slug/': typeof FeedSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/inngest'
    | '/api/notifications'
    | '/feed/$slug'
    | '/feed/$slug/$articleSlug'
    | '/feed/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/inngest'
    | '/api/notifications'
    | '/feed/$slug/$articleSlug'
    | '/feed/$slug'
  id:
    | '__root__'
    | '/'
    | '/api/inngest'
    | '/api/notifications'
    | '/feed/$slug'
    | '/feed/$slug/$articleSlug'
    | '/feed/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiInngestRoute: typeof ApiInngestRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  FeedSlugRoute: typeof FeedSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$slug': {
      id: '/feed/$slug'
      path: '/feed/$slug'
      fullPath: '/feed/$slug'
      preLoaderRoute: typeof FeedSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/$slug/': {
      id: '/feed/$slug/'
      path: '/'
      fullPath: '/feed/$slug/'
      preLoaderRoute: typeof FeedSlugIndexRouteImport
      parentRoute: typeof FeedSlugRoute
    }
    '/feed/$slug/$articleSlug': {
      id: '/feed/$slug/$articleSlug'
      path: '/$articleSlug'
      fullPath: '/feed/$slug/$articleSlug'
      preLoaderRoute: typeof FeedSlugArticleSlugRouteImport
      parentRoute: typeof FeedSlugRoute
    }
  }
}

interface FeedSlugRouteChildren {
  FeedSlugArticleSlugRoute: typeof FeedSlugArticleSlugRoute
  FeedSlugIndexRoute: typeof FeedSlugIndexRoute
}

const FeedSlugRouteChildren: FeedSlugRouteChildren = {
  FeedSlugArticleSlugRoute: FeedSlugArticleSlugRoute,
  FeedSlugIndexRoute: FeedSlugIndexRoute,
}

const FeedSlugRouteWithChildren = FeedSlugRoute._addFileChildren(
  FeedSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiInngestRoute: ApiInngestRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  FeedSlugRoute: FeedSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
